/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_frame;


import Controlador.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis Gardez
 */
public class Calculo_mojones_lote extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calculo_poligono_base
     */
    DefaultTableModel model;

    public Calculo_mojones_lote() {
        initComponents();
        cargar();
        this.setLocation(325, 0);
    }

    void cargar() {
        try {
            conectar cx = new conectar();
            Connection cc = cx.getConnection();

            String modelo[] = {"idRegistro", "Estacion", "Distancia", "Deflexion", "Rumbo", "Norte", "Sur", "Este", "Oeste", "Latitud", "Longitud ", "Doble_Longitud ", "Positiva", "Negativa"};
            model = new DefaultTableModel(null, modelo);
            String sql = "SELECT * FROM calculo_mojones_lote";
            Object registro[] = new Object[14];
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                registro[0] = rs.getString("idregistro");
                registro[1] = rs.getString("Estacion");
                registro[2] = rs.getString("Distancia");
                registro[3] = rs.getString("Deflexion");
                registro[4] = rs.getString("Rumbo");
                registro[5] = rs.getString("Norte");
                registro[6] = rs.getString("Sur");
                registro[7] = rs.getString("Este");
                registro[8] = rs.getString("Oeste");

                registro[9] = rs.getString("Latitud");
                registro[10] = rs.getString("Longitud");
                registro[11] = rs.getString("Doble_Longitud");
                registro[12] = rs.getString("Positivo");
                registro[13] = rs.getString("Negativo");
                model.addRow(registro);
            }
            tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Calculo_mojones_lote.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Calculo_Mojones_lote");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 986, 427));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
